### ISSUE TITLE
Camera import error

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#266]
I feel pretty confident that the identity of the camera is being pulled from the initial hardware part of the configuration file, not the 'low' or 'high' regions later on...

```
hardware:
  daq:
    type: NI
  camera:
    -
      type: HamamatsuOrca
      serial_number: 302352
    -
      type: HamamatsuOrca
      serial_number: 302158
```
